/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBO_H_RPCGEN
#define _FIBO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define FIBO_PROG 12345678
#define FIBO_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define FIBO 1
extern  u_int * fibo_1(u_int *, CLIENT *);
extern  u_int * fibo_1_svc(u_int *, struct svc_req *);
extern int fibo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIBO 1
extern  u_int * fibo_1();
extern  u_int * fibo_1_svc();
extern int fibo_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBO_H_RPCGEN */
